const int LED_PIN=13;

void setup() {
  pinMode(LED_PIN, OUTPUT);
}

void loop() {
  digitalWrite(13, HIGH);  //light on...
  delay(250);                   //... for some time...
  digitalWrite(13, LOW);   //light off...
  delay(250);                   //... for some time...
}
